apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dxn65prrd-go
  janus-idp.io/tekton: dxn65prrd-go
  backstage.io/kubernetes-id: dxn65prrd-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dxn65prrd-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
