apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dxn65prrd-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dxn65prrd-go 
  name: dxn65prrd-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dxn65prrd-go 
